const INTENTS = {

    LOW_STOCK: "LOW_STOCK",

    OUT_OF_STOCK: "OUT_OF_STOCK",

    INVENTORY: "INVENTORY",

    SEARCH_PRODUCT: "SEARCH_PRODUCT",

    AVAILABLE_STOCK: "AVAILABLE_STOCK",

    SUPPLIER: "SUPPLIER",

    PURCHASE_ORDER: "PURCHASE_ORDER",

    DASHBOARD: "DASHBOARD",

    GENERAL: "GENERAL"

};

module.exports = INTENTS;